name: Test Bot on Develop

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/chechkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pytest --maxfail=5 --diable-warnings
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          MY_GITHUB_API_URL: ${{ secrets.MY_GITHUB_API_URL }}
          MY_GITHUB_ORG: ${{ secrets.MY_GITHUB_ORG }}
          MY_GITHUB_PROJECT_NUMBER: ${{ secrets.MY_GITHUB_PROJECT_NUMBER }}